[build.environment]
HUGO_VERSION = "0.146.6"
NODE_VERSION = "23.10.0"
TZ = "America/Los_Angeles"
RUBY_VERSION = "3.3.4"


[build]
command = "gem install --no-document asciidoctor && hugo --gc --minify"
publish = "public"

